name: sirciam_app
description: Sistema de Registro y Control de Asistencia del SIRCIAM
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.0
  path: ^1.8.0
  flutter_secure_storage: ^8.0.0
  crypto: ^3.0.2
  encrypt: ^5.0.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  intl: ^0.18.0
  path_provider: ^2.1.2
  http: ^1.1.0
  provider: ^6.0.5
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.1.1
  flutter_pdfview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/mimp.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/mimp.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_mimp.png
